trigger:
# defines what triggers the pipeline to run
  branches:
    include:
      - main # any pushes to main
  paths:
    exclude: # these files do not trigger the pipeline
    - 'README.md'
    - '.gitignore'

pool:
  name: 'ccse-2-agent'

variables:
  #pythonVersion: '3.12.10'
  pythonVersion: '3.12'
  SNYK_TOKEN: '19b1c0e8-d849-4ed2-b3af-38665726a2ba'

stages:
- stage: CI
  displayName: 'CI'
  jobs:

  - job: ci_job
    displayName: 'CI (Including Snyk Scan)'
    steps:

    - script: |
        sudo apt update
        sudo apt install -y python3 python3-pip
        python3 --version
        python3 -m pip --version
      displayName: 'Python and pip installation.'

    - script: |
        sudo apt install -y python3.12-venv
        python3 -m venv env
        source env/bin/activate
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        sudo apt install -y npm
        sudo npm install -g snyk

      displayName: 'Install Snyk CLI'

    - script: |
        snyk auth $(SNYK_TOKEN)
      displayName: 'Authenticate Snyk'

    - script: |
        snyk test --file=requirements.txt --severity-threshold=high --command=$(System.DefaultWorkingDirectory)/env/bin/python3
      displayName: 'Run Snyk Scan'

    - script: |
        sudo systemctl restart securecart
      displayName: 'Deploy Code to Existing Folder on VM'
