# Generated by Django 5.1.5 on 2025-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_and_potions', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default.jpg', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
