# Generated by Django 5.1.5 on 2025-02-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_and_potions', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Shipped', 'Shipped')], default='Pending', max_length=50),
        ),
    ]
