# Generated by Django 5.1.5 on 2025-02-08 16:12

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic_and_potions', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=encrypted_model_fields.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=encrypted_model_fields.fields.EncryptedIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
    ]
